version: '3.8'

services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - '5134:5432'
    restart: always
